using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;
using System.Data;
using System.Threading.Tasks;

using System.Runtime.InteropServices;



#if UNITY_EDITOR
using UnityEditor;
#endif


public enum Labels {
    NonInteractable,
    Switch,
    LightIntensityKnob,
    CondenserKnob,
    RevolvingNosepiece,
    CoarseFocusKnob,
    FineFocusKnob,
    OcularKnob,
    OcularLens,
    SpecimenHolder,
    StageKnob,
    SpecimenHolderKnob,
    Slide,
    ApertureKnob,
    ImmersionOil,
    ImmersionOilCap
}


public enum Languages {
    EN = 0,
    GR = 1
}



public class GameCursor {

    public Texture2D Shape;
    public Vector2 Offset;

    public GameCursor (Texture2D _Shape, Vector2 _Offset) {
        Shape = _Shape;
        Offset = _Offset;
    }

}


public class OrdinaryNames {

    public List<string> LanguageSpecificNames = new List<string> ();

    public OrdinaryNames (string _NameEn, string _NameGr) {
        LanguageSpecificNames.Add (_NameEn);
        LanguageSpecificNames.Add (_NameGr);
    }

}


public class MouseUI : MonoBehaviour {

    static GameObject Ego;

    static Texture2D WedgeCursor, FingerCursor, HandCursor, GrabCursor, PressingFingerCursor, EyeCursor;

    static int Wedge = 0;
    static int Finger = 1;
    static int ClickingFinger = 2;
    static int Hand = 3;
    static int Grab = 4;
    static int Eye = 5;

    static int CurrentCursor;

    static List<GameCursor> Cursors;

    static Event occurence;

    static int Tooltip_MiddleX;
    static int Tooltip_MiddleY;

    static int Tooltip_SizeX;
    static int Tooltip_SizeY;

    static Vector2 Coords_for_FrozenToolTip;

    static string Text_for_Tooltip;

    static Texture2D TooltipBG;

    public Labels Label;

    [HideInInspector]
    public bool Zoomable, Pressable, Rotatable, Movable, Receptable;

    [HideInInspector]
    public GameObject Place;

    [HideInInspector]
    public bool TemporarilyInaccessible;

    string UserFriendlyName;

    static Camera mainCamera;

    static GameObject ObjectHoveringOver;
    public static GameObject ObjectBeingCarried;

    Vector3 VectorDistance_from_Camera;

    const float MinimumDistance_for_Interaction = 2F;

    static GameObject ObjectMouseIsDownOn;

    public static bool Rotating; //public because called by EgoController, too

    static Vector3 RayHitPoint_for_MouseDown;

    static bool UsingTwoObjectsTogether;

    #region Editor
#if UNITY_EDITOR

    [CustomEditor (typeof (MouseUI)), CanEditMultipleObjects]
    public class MouseUI_Editor : Editor {

        public override void OnInspectorGUI () {

            base.OnInspectorGUI ();

            MouseUI mouseUI = (MouseUI)target;

            if (mouseUI.Label != Labels.NonInteractable) {
                showAttributes (mouseUI);
                assignBooleanValues (mouseUI);
            }

            if (mouseUI.Movable)
                showPlace (mouseUI);

        }

        void showAttributes (MouseUI _mouseUI) {

            EditorGUILayout.BeginVertical ();

            _mouseUI.Zoomable = EditorGUILayout.Toggle ("Zoomable", _mouseUI.Zoomable);
            _mouseUI.Pressable = EditorGUILayout.Toggle ("Pressable", _mouseUI.Pressable);
            _mouseUI.Rotatable = EditorGUILayout.Toggle ("Rotatable", _mouseUI.Rotatable);
            _mouseUI.Movable = EditorGUILayout.Toggle ("Movable", _mouseUI.Movable);
            _mouseUI.Receptable = EditorGUILayout.Toggle ("Receptable", _mouseUI.Receptable);

            EditorGUILayout.EndVertical ();

        }

        void assignBooleanValues (MouseUI _mouseUI) {

            _mouseUI.Zoomable = BooleanValues[_mouseUI.Label][0];
            _mouseUI.Pressable = BooleanValues[_mouseUI.Label][1];
            _mouseUI.Rotatable = BooleanValues[_mouseUI.Label][2];
            _mouseUI.Movable = BooleanValues[_mouseUI.Label][3];
            _mouseUI.Receptable = BooleanValues[_mouseUI.Label][4];
        }


        void showPlace (MouseUI _mouseUI) {

            EditorGUILayout.Space ();

            _mouseUI.Place = EditorGUILayout.ObjectField ("Place", _mouseUI.Place, typeof (GameObject), true) as GameObject;
        
        }

    }

#endif
    #endregion


    // Start is called before the first frame update
    void Start () {

        Ego = GameObject.Find ("Ego");

        WedgeCursor = Resources.Load ("wedge") as Texture2D;
        FingerCursor = Resources.Load ("finger") as Texture2D;
        PressingFingerCursor = Resources.Load ("pressing_finger") as Texture2D;
        HandCursor = Resources.Load ("hand") as Texture2D;
        GrabCursor = Resources.Load ("grab") as Texture2D;
        EyeCursor = Resources.Load ("eye") as Texture2D;

        Cursors = new List<GameCursor> ();

        Cursors.Add (new GameCursor (WedgeCursor, Vector2.zero));
        Cursors.Add (new GameCursor (FingerCursor, new Vector2 (9, 2)));
        Cursors.Add (new GameCursor (PressingFingerCursor, new Vector2 (9, 2)));
        Cursors.Add (new GameCursor (HandCursor, new Vector2 (11, 3)));
        Cursors.Add (new GameCursor (GrabCursor, new Vector2 (7, 2)));
        Cursors.Add (new GameCursor (EyeCursor, new Vector2 (12, 12)));

        Tooltip_MiddleX = 120;
        Tooltip_SizeX = 2 * Tooltip_MiddleX;

        Tooltip_SizeY = 50;
        Tooltip_MiddleY = Tooltip_SizeY + 5;

        TooltipBG = Resources.Load ("ui_tooltip") as Texture2D;

        mainCamera = Camera.main;

        ObjectHoveringOver = null;

        ObjectBeingCarried = null;

        ObjectMouseIsDownOn = null;

        Rotating = false;

        TemporarilyInaccessible = false;

        UserFriendlyName = AttributedName (Label);

        CurrentCursor = Wedge;

        RayHitPoint_for_MouseDown = Vector3.zero;

        UsingTwoObjectsTogether = false;

    }



    static void switchCursor (int _CursorID) {

        CurrentCursor = _CursorID;

        Cursor.SetCursor (Cursors[CurrentCursor].Shape, Cursors[CurrentCursor].Offset, CursorMode.Auto);

    }


    public static void callOnGUI () {

#if !UNITY_EDITOR
        if (EgoController.CursorFrozen)
            DisplayFakeCursor ();
#endif

        occurence = Event.current;

        if (!UsingTwoObjectsTogether && !Rotating && ObjectHoveringOver != null &&
            ObjectBeingCarried != ObjectHoveringOver &&
            ObjectHoveringOver.GetComponent<MouseUI> ().Label != Labels.NonInteractable) {

            DisplayTooltip ();
        }
        else if (Rotating)
            DisplayFrozenTooltip ();

    }


    static void DisplayFakeCursor () {
        if (!UsingTwoObjectsTogether)
            GUI.DrawTexture (new Rect (Screen.width / 2 - Cursors[CurrentCursor].Offset.x,
                Screen.height / 2 - Cursors[CurrentCursor].Offset.y, 32, 32),
                Cursors[CurrentCursor].Shape);
    }


    static void DisplayTooltip () {
        GUI.skin.box.alignment = TextAnchor.MiddleCenter;
        GUI.skin.box.normal.background = TooltipBG;
        GUI.skin.box.fontSize = 16;
        GUI.skin.box.normal.textColor = UnityEngine.Color.yellow;
        GUI.backgroundColor = new UnityEngine.Color (0F, 0F, 0F, 0.3F);
        GUI.Box (new Rect (occurence.mousePosition.x - Tooltip_MiddleX,
            occurence.mousePosition.y - Tooltip_MiddleY, Tooltip_SizeX, Tooltip_SizeY),
            Text_for_Tooltip);
    }


    static void DisplayFrozenTooltip () {
        GUI.skin.box.alignment = TextAnchor.MiddleCenter;
        GUI.skin.box.normal.background = TooltipBG;
        GUI.skin.box.fontSize = 16;
        GUI.skin.box.normal.textColor = UnityEngine.Color.yellow;
        GUI.backgroundColor = new UnityEngine.Color (0F, 0F, 0F, 0.3F);
        GUI.Box (new Rect (Coords_for_FrozenToolTip.x - Tooltip_MiddleX,
                Coords_for_FrozenToolTip.y - Tooltip_MiddleY, Tooltip_SizeX, Tooltip_SizeY),
                Text_for_Tooltip);
    }


    void OnMouseOver () {

        if (Label != Labels.NonInteractable && !TemporarilyInaccessible && (!Movable ||
            EgoController.PermittingCollection_of_Objects[Ego.GetComponent<EgoController> ().Mode])) {

            VectorDistance_from_Camera = transform.position - mainCamera.transform.position;

            if (!Rotating && VectorDistance_from_Camera.magnitude < MinimumDistance_for_Interaction) {

                Text_for_Tooltip = UserFriendlyName;

                if (ObjectBeingCarried == null && ObjectMouseIsDownOn == null) {

                    ObjectHoveringOver = gameObject;

                    if (Pressable)
                        switchCursor (Finger);
                    else if (Zoomable)
                        switchCursor (Eye);
                    else if (Rotatable || Movable)
                        switchCursor (Hand);

                } else if (Receptable && ObjectBeingCarried != null)
                    //cursor is already grab in this case
                    ObjectHoveringOver = gameObject;

            }

        }
    
    }


    void OnMouseExit () {

            if (Label != Labels.NonInteractable && !Rotating) {

                ObjectHoveringOver = null;

                if (ObjectBeingCarried == null)
                    switchCursor (Wedge);
                else
                    switchCursor (Grab);

            }        

    }



    void OnMouseDown () {

        if (Label != Labels.NonInteractable && 
            ObjectHoveringOver == gameObject) {

            ObjectMouseIsDownOn = gameObject;

            if (Movable && ObjectBeingCarried == null) {//in case a movable is also a receptable, e.g. immersion oil; in this case, we want the cursor to be grab with mouse down only if not carrying another object

                switchCursor (Grab);

            } else if (Rotatable && !Rotating && ObjectBeingCarried == null) {

                Coords_for_FrozenToolTip =
                    new Vector2 (occurence.mousePosition.x, occurence.mousePosition.y);

                switchCursor (Grab);

            } else if (Pressable) {

                GetComponent<InteractableObject> ().press ();

                switchCursor (ClickingFinger);

            } else if (Zoomable) {

                GetComponent<InteractableObject> ().zoom ();

                switchCursor (Wedge);

            } else if (Receptable && ObjectBeingCarried != null) {

                switchCursor (Hand);

            }

        } else if (ObjectBeingCarried != null && tag == "Bench") {

            //first ray casted - when mouse is down
            Ray ray = mainCamera.ScreenPointToRay (Input.mousePosition);
            RaycastHit hit;

            Physics.Raycast (ray, out hit);

            VectorDistance_from_Camera = hit.point - mainCamera.transform.position;

            if (VectorDistance_from_Camera.magnitude < MinimumDistance_for_Interaction) {

                RayHitPoint_for_MouseDown = hit.point;

                switchCursor (Hand);

            }

        }

    }




    void OnMouseDrag () {

        if (Rotatable && ObjectMouseIsDownOn == gameObject) {//the check whether ObjectMouseIsDownOn has the value of the current gameObject secures that a knob cannot be rotated when Ego is too far away (having the value, means that it has gone through OnMouseOver which filters out the interaction with long distant interactable objects)

            Rotating = true;

            float mouse_dx = Input.GetAxis ("Mouse X");
            float mouse_dy = Input.GetAxis ("Mouse Y");

            if (mouse_dx != 0F || mouse_dy != 0F)
                GetComponent<InteractableObject> ().rotate (new Vector2 (mouse_dx, -mouse_dy));

        }

    }



    async Task OnMouseUp () {

        if (Rotating) {

            GetComponent<InteractableObject> ().doneRotating ();

            Rotating = false;

            switchCursor (Wedge); //if the cursor stops over the rotatable, it will immediately become a hand due to OnMouseOver()

        } else if (Label != Labels.NonInteractable) {

            if (ObjectMouseIsDownOn == gameObject && ObjectHoveringOver == gameObject) {

                if (Movable && ObjectBeingCarried == null) { //clicking on an object to pick it up

                    setInteractivity (false);

                    if (Place != null 
                        && Place.GetComponent<InteractableObject>())
                        Place.GetComponent<InteractableObject> ().evacuate (gameObject);

                    Ego.GetComponent<EgoController> ().attach (gameObject);

                    ObjectBeingCarried = gameObject;

                    switchCursor (Grab);

                } else if (Receptable && ObjectBeingCarried != null) {//clicking on an object to put the object being carried on it

                    await tryUsingTogether_with_ObjectBeingCarried ();
                    
                    //cursor and ObjectBeingCarried variable are being dealt inside tryUsingTogether_with_ObjectBeingCarried()

                }

            }

        } else if (ObjectBeingCarried != null && tag == "Bench") {

            //second ray casted - when mouse is up
            Ray ray = mainCamera.ScreenPointToRay (Input.mousePosition);
            RaycastHit hit;

            Physics.Raycast (ray, out hit);

            if (MathFunctions.ApproximateProximity_of (RayHitPoint_for_MouseDown, hit.point, 0.1F)
                && !ObjectBeingCarried.GetComponent<MouseUI> ().AreThereObjects_around (hit.point)) {

                ObjectBeingCarried.transform.SetParent (null);

                ObjectBeingCarried.GetComponent<MovableObject> ().restoreUprightRotation ();

                ObjectBeingCarried.transform.position = new Vector3 (hit.point.x, hit.point.y + ObjectBeingCarried.GetComponent<MovableObject> ().Y_Offset_for_Relocation, hit.point.z);

                ObjectBeingCarried.GetComponent<MouseUI> ().setInteractivity (true);

                ObjectBeingCarried = null;

            } else
                switchCursor (Grab);

        }

        ObjectMouseIsDownOn = null;

        ObjectHoveringOver = null; //it needs to be set to null every time, otherwise the tooltip may continue after done rotating a knob
    
    }


    async Task tryUsingTogether_with_ObjectBeingCarried () {

//#if UNITY_EDITOR
//        Cursor.visible = false;
//No point to hide the cursor in Editor mode, since it's always visible.

        UsingTwoObjectsTogether = true;

        Values_After_JointUse ResultValues = await GetComponent<InteractableObject> ().use_with (ObjectBeingCarried);

        UsingTwoObjectsTogether = false;

//#if UNITY_EDITOR
//        Cursor.visible = true;

        if (ResultValues.JointUse_TookPlace) {

            setInteractivity (ResultValues.Receptor_NewInteractivity);
            //Receptor's handling needs to be BEFORE ObjectBeingCarried's because ObjectBeingCarried might become child of Receptor

            if (ResultValues.Receptor_NewPlace != null)
                Place = ResultValues.Receptor_NewPlace;

            ObjectBeingCarried.GetComponent<MouseUI> ().setInteractivity (ResultValues.ObjectBeingCarried_NewInteractivity);
            //interactivity of ObjectBeingCarried needs to be set BEFORE potentially changing its value to null

            if (ResultValues.ObjectBeingCarried_NewPlace != null) {

                ObjectBeingCarried.GetComponent<MouseUI> ().Place = ResultValues.ObjectBeingCarried_NewPlace;

                ObjectBeingCarried = null;

                switchCursor (Wedge);

            } else {//if continuing carrying the object, e.g. after using immersion oil with slide

                Ego.GetComponent<EgoController> ().attach (ObjectBeingCarried); //in case it has been detached (e.g. the immersion oil has become child of slide)

                switchCursor (Grab);
            
            }
        
        }

    }


    bool AreThereObjects_around (Vector3 _HitPoint) {

        Collider[] OtherColliders = Physics.OverlapSphere (_HitPoint, GetComponent<MeshRenderer> ().bounds.size.magnitude / 2);

        for (int i = 0; i < OtherColliders.Length; i++) {

            if (OtherColliders[i].gameObject.tag != "Bench" && 
                OtherColliders[i].gameObject.tag != "Room") {

                return true;

            }

        }

            return false;

    }




public void setInteractivity (bool _InteractivityState) {

        for (int i = 0; i < GetComponents<BoxCollider> ().Length; i++)
            GetComponents<BoxCollider> ()[i].enabled = _InteractivityState;

        for (int i = 0; i < transform.childCount; i++) {

            if (transform.GetChild (i).GetComponent<MouseUI> ())
                transform.GetChild (i).GetComponent<MouseUI> ().setInteractivity (_InteractivityState);

        }

    }


    static readonly Dictionary<Labels, OrdinaryNames> NameAttribution = new Dictionary<Labels, OrdinaryNames> {
        {Labels.NonInteractable, new OrdinaryNames(null,null)},
        {Labels.Switch, new OrdinaryNames ("SWITCH","диайоптгс")},
        {Labels.LightIntensityKnob, new OrdinaryNames ("LIGHT INTENSITY KNOB","йовкиас емтасгс жытос")},
        {Labels.CondenserKnob, new OrdinaryNames ("CONDENSER KNOB","йовкиас сулпуймытг")},
        {Labels.RevolvingNosepiece, new OrdinaryNames ("REVOLVING NOSEPIECE","пеяистяежолемг йежакг")},
        {Labels.CoarseFocusKnob, new OrdinaryNames("COARSE FOCUS KNOB", "адяос йовкиас")},
        {Labels.FineFocusKnob, new OrdinaryNames("FINE FOCUS KNOB", "лийяолетяийос йовкиас")},
        {Labels.OcularKnob, new OrdinaryNames ("OCULAR LENS","пяосожхаклиос жайос")},
        {Labels.OcularLens, new OrdinaryNames ("OCULAR LENS","пяосожхаклиос жайос")},
        {Labels.SpecimenHolder, new OrdinaryNames ("SPECIMEN HOLDER", "одгцос деицлатос")},
        {Labels.StageKnob, new OrdinaryNames ("STAGE KNOB","йовкиас тяапефас")},
        {Labels.SpecimenHolderKnob, new OrdinaryNames ("SPECIMEN HOLDER KNOB","йовкиас одгцоу деицлатос")},
        {Labels.Slide, new OrdinaryNames ("SPECIMEN","деицла")},
        {Labels.ApertureKnob, new OrdinaryNames ("APERTURE KNOB","ловкос ияидас")},
        {Labels.ImmersionOil, new OrdinaryNames ("IMMERSION OIL", "йедяекаио")},
        {Labels.ImmersionOilCap, new OrdinaryNames ("CAP", "йапайи")}
    };

    public static string AttributedName (Labels _NameLabel) {
        return NameAttribution[_NameLabel].LanguageSpecificNames[(int)Specs.Language];
    }


    public static readonly Dictionary<Labels, List<bool>> BooleanValues =
        new Dictionary<Labels, List<bool>> () {
        //1st: Zoomable; 2nd: Pressable; 3rd: Rotatable; 4th: Movable; 5th: Receptable
        {Labels.Switch, new List<bool> {false,true,false,false,false }},
        {Labels.LightIntensityKnob, new List<bool> {false,false,true,false,false}},
        {Labels.CondenserKnob, new List<bool> {false,false,true,false,false}},
        {Labels.RevolvingNosepiece, new List<bool> {false,false,true,false,false}},
        {Labels.CoarseFocusKnob, new List<bool> {false,false,true,false,false}},
        {Labels.FineFocusKnob, new List<bool> {false,false,true,false,false}},
        {Labels.OcularKnob, new List<bool> {false,false,true,false,false}},
        {Labels.OcularLens, new List<bool> {true,false,false,false,false}},
        {Labels.SpecimenHolder, new List<bool> {false,false,false,false,true}},
        {Labels.StageKnob, new List<bool> {false,false,true,false,false}},
        {Labels.SpecimenHolderKnob, new List<bool> {false,false,true,false,false}},
        {Labels.Slide, new List<bool> {false,false,false,true,true}},
        {Labels.ApertureKnob, new List<bool> {false,false,true,false,false}},
        {Labels.ImmersionOil, new List<bool> {false,false,false,true,true}},
        {Labels.ImmersionOilCap, new List<bool> {false,false,false,true,false}}
    };


}
